name: react.js CI

on:
  push:
    branches: [ main ]
  pull_requests:
    branches: [ main ]
    
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use react.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        yarn
        yarn build